server:
  port: 7001

eureka:
  instance:
    hostname: localhost
  client:
    #flase代表不想自己注册自己
    register-with-eureka: false
    #flase表示自己是注册中心 我的职责是维护服务实例  并不需要检索服务
    fetch-registry: false
    service-url:
      # 设置与 Eureka Server 交互的地址，查询服务 和 注册服务都依赖这个地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
