
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  application:
    name: cloud-payment-service # 项目名,也是注册的名字

eureka:
  client:
    # 注册进 Eureka 的服务中心
    register-with-eureka: true
    # 检索 服务中心 的其它服务
    fetch-registry: true
    service-url:
      # 设置与 Eureka Server 交互的地址
      defaultZone: http://localhost:7001/eureka/
server:
  port: 7002

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hcy.springcloud.entities  # 所有Entity 别名类所在包
